version: '3'

services:
  server:
    build: ./server
    volumes:
      - ./server:/usr/src/app
    ports:
      - 5000:5000
  
  client:
    build: ./client
    volumes:
      - ./client/public:/app/public
      - ./client/src:/app/src
      - ./client/babel.config.js:/app/babel.config.js
    ports:
      - 8080:8080
    depends_on:
      - server