"""empty message

Revision ID: 8135380674ed
Revises: 9930f7f0efbe
Create Date: 2019-09-04 23:19:38.432518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8135380674ed'
down_revision = '9930f7f0efbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('creator_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'games', 'users', ['creator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'games', type_='foreignkey')
    op.drop_column('games', 'creator_id')
    # ### end Alembic commands ###
